name: ios-mcn-ran-uni-build

on:
  push:
    tags:
      - 'v*'   # Triggers only on tags starting with 'v' like v1.0, v2.1.3 etc.
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Docker image tag name (e.g. v0.1.4.rc5)'
        required: true

jobs:

  authcheck:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      DOCKER_REGISTRY: ghcr.io/
      DOCKER_REPOSITORY: ${{ github.repository_owner }}/
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GHCRUSER }}
          password: ${{ secrets.GHCRPASS }}

      - name: Checkout with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GHCRPASS }}

  ran-base-uni:
    runs-on: ubuntu-latest
    needs: authcheck
    env:
      REGISTRY: ghcr.io
      DOCKER_REGISTRY: ghcr.io/
      DOCKER_REPOSITORY: ${{ github.repository_owner }}/
    steps:
      - name: Extract tag name
        run: |
          if [ -z "${{ github.event.inputs.tag_name }}" ]; then
            echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "TAG_NAME=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
          fi

      - name: Login to ghcr.io
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GHCRUSER }}
          password: ${{ secrets.GHCRPASS }}

      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GHCRPASS }}

      - name: Build and push "Dockerfile.base.ubuntu22" Docker image
        run: |
          docker build --build-arg GHPASS=${{ secrets.GHCRPASS }} \
            -t ghcr.io/${{ github.repository_owner }}/ran-base-uni:${{ env.TAG_NAME }} \
            -f docker/Dockerfile.base.ubuntu22 .
          docker push ghcr.io/${{ github.repository_owner }}/ran-base-uni:${{ env.TAG_NAME }}

  ran-build-uni:
    runs-on: ubuntu-latest
    needs: ran-base-uni
    env:
      REGISTRY: ghcr.io
      DOCKER_REGISTRY: ghcr.io/
      DOCKER_REPOSITORY: ${{ github.repository_owner }}/
    steps:
      - name: Extract tag name
        run: |
          if [ -z "${{ github.event.inputs.tag_name }}" ]; then
            echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "TAG_NAME=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
          fi

      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GHCRPASS }}

      - name: Login to ghcr.io
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GHCRUSER }}
          password: ${{ secrets.GHCRPASS }}

      - name: Build and push "Dockerfile.build.ubuntu22" Docker image
        run: |
          docker build --build-arg DOCKER_REPOSITORY=${{ github.repository_owner }} \
            --build-arg VERSION=${{ env.TAG_NAME }} \
            -t ghcr.io/${{ github.repository_owner }}/ran-build-uni:${{ env.TAG_NAME }} \
            -f docker/Dockerfile.build.ubuntu22 .
          docker push ghcr.io/${{ github.repository_owner }}/ran-build-uni:${{ env.TAG_NAME }}

  ran-build-fhi72-uni:
    runs-on: ubuntu-latest
    needs: ran-base-uni
    env:
      REGISTRY: ghcr.io
      DOCKER_REGISTRY: ghcr.io/
      DOCKER_REPOSITORY: ${{ github.repository_owner }}/
    steps:
      - name: Extract tag name
        run: |
          if [ -z "${{ github.event.inputs.tag_name }}" ]; then
            echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "TAG_NAME=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
          fi

      - uses: actions/checkout@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GHCRUSER }}
          password: ${{ secrets.GHCRPASS }}

      - name: Build and push "Dockerfile.build.fhi72.ubuntu22" Docker image
        run: |
          docker build \
            --build-arg DOCKER_REPOSITORY=${{ github.repository_owner }} \
            --build-arg VERSION=${{ env.TAG_NAME }} \
            --build-arg GIT_TOKEN=${{ secrets.GHCRPASS }} \
            -t ghcr.io/${{ github.repository_owner }}/ran-build-fhi72-uni:${{ env.TAG_NAME }} \
            -f docker/Dockerfile.build.fhi72.ubuntu22 .
          docker push ghcr.io/${{ github.repository_owner }}/ran-build-fhi72-uni:${{ env.TAG_NAME }}

  ran-gnb-uni:
    runs-on: ubuntu-latest
    needs: [ran-base-uni, ran-build-uni]
    env:
      REGISTRY: ghcr.io
      DOCKER_REGISTRY: ghcr.io/
      DOCKER_REPOSITORY: ${{ github.repository_owner }}/
    steps:
      - name: Extract tag name
        run: |
          if [ -z "${{ github.event.inputs.tag_name }}" ]; then
            echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "TAG_NAME=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
          fi

      - uses: actions/checkout@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GHCRUSER }}
          password: ${{ secrets.GHCRPASS }}

      - name: Build and push "Dockerfile.gNB.ubuntu22" Docker image
        run: |
          docker build --build-arg DOCKER_REPOSITORY=${{ github.repository_owner }} \
            --build-arg VERSION=${{ env.TAG_NAME }} \
            -t ghcr.io/${{ github.repository_owner }}/ran-gnb-uni:${{ env.TAG_NAME }} \
            -f docker/Dockerfile.gNB.ubuntu22 .
          docker push ghcr.io/${{ github.repository_owner }}/ran-gnb-uni:${{ env.TAG_NAME }}

  ran-gnb-fhi72-uni:
    runs-on: ubuntu-latest
    needs: [ran-base-uni, ran-build-fhi72-uni]
    env:
      REGISTRY: ghcr.io
      DOCKER_REGISTRY: ghcr.io/
      DOCKER_REPOSITORY: ${{ github.repository_owner }}/
    steps:
      - name: Extract tag name
        run: |
          if [ -z "${{ github.event.inputs.tag_name }}" ]; then
            echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "TAG_NAME=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GHCRUSER }}
          password: ${{ secrets.GHCRPASS }}

      - name: Build and push "Dockerfile.gNB.fhi72.ubuntu22" Docker image

        run: |
          docker build --build-arg DOCKER_REPOSITORY=${{ github.repository_owner }} \
            --build-arg VERSION=${{ env.TAG_NAME }} \
            -t ghcr.io/${{ github.repository_owner }}/ran-gnb-fhi72-uni:${{ env.TAG_NAME }} \
            -f docker/Dockerfile.gNB.fhi72.ubuntu22 .
          docker push ghcr.io/${{ github.repository_owner }}/ran-gnb-fhi72-uni:${{ env.TAG_NAME }}
  ios-mcn-nr-ue:
    runs-on: ubuntu-latest
    needs: [ran-base-uni, ran-build-uni]
    permissions:
      contents: read
    env:
      REGISTRY: ghcr.io
      DOCKER_REGISTRY: ghcr.io/
      DOCKER_REPOSITORY: ${{ github.repository_owner }}/
    steps:
      - name: Extract tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - name: Login to ghcr Hub
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GHCRUSER }}
          password: ${{ secrets.GHCRPASS }}

      - name: Build and push "Dockerfile.nrUE.ubuntu22" Docker image
        run: |
          docker build --build-arg DOCKER_REPOSITORY=${{ github.repository_owner }} \
           --build-arg VERSION=${{ env.TAG_NAME }} \
           -t ghcr.io/${{ github.repository_owner }}/ios-mcn-nr-ue-uni:${{ env.TAG_NAME }} -f docker/Dockerfile.nrUE.ubuntu22 .
          docker push ghcr.io/${{ github.repository_owner }}/ios-mcn-nr-ue-uni:${{ env.TAG_NAME }}
