#!/bin/bash

set -e

if [[ ! -f /etc/os-release ]]; then
  echo "No /etc/os-release file found. You're likely on an unsupported distro."
  exit -1
fi
OS_DISTRO=$(grep "^ID=" /etc/os-release | sed "s/ID=//" | sed "s/\"//g")
OS_RELEASE=$(grep "^VERSION_ID=" /etc/os-release | sed "s/VERSION_ID=//" | sed "s/\"//g")
case "$OS_DISTRO" in
  ubuntu) OS_BASEDISTRO="debian"; INSTALLER="apt-get"; CMAKE="cmake" ;;
esac
KERNEL_VERSION=$(uname -r | cut -d '.' -f1)
KERNEL_MAJOR=$(uname -r | cut -d '.' -f2)

###############################
## echo and  family
###############################
# only emit color if connected to a terminal, and if it supports colors
if [ -t 1 ]; then
  num_colors=$(tput colors)
  if [ -n "$num_colors" ] && [ "$num_colors" -ge 8 ]; then
    red='\E[31m'
    green='\E[32m'
    yellow='\E[33m'
    blue='\E[1;34m'
    reset_color='\E[00m'
  fi
fi

cecho()  {
    # Color-echo
    # arg1 = message
    # arg2 = color
    local default_msg="No Message."
    message=${1:-$default_msg}
    color=${2:-$green}
    echo -e "$color$message$reset_color"
    return
}

echo_error()   { cecho "$*" $red          ;}
echo_fatal()   { cecho "$*" $red; exit -1 ;}
echo_warning() { cecho "$*" $yellow       ;}
echo_success() { cecho "$*" $green        ;}
echo_info()    { cecho "$*" $blue         ;}

########################
# distribution helpers #
########################

# This function return a string to identify the distribution we are running
# If we can't check the distribution, it returns "Unknown"
# This function return always true as exit code by design
# Examples:
#   debian8.5
get_distribution_release() {
    if [[ ! -z "$OS_DISTRO$OS_RELEASE" ]]; then
        echo "$OS_DISTRO$OS_RELEASE"
    else
        echo Unknown
    fi
}

check_supported_distribution() {
    local distribution=$(get_distribution_release)
    case "$distribution" in
        "ubuntu22.04") return 0 ;;
        "ubuntu20.04") return 0 ;;
        "ubuntu24.04") return 0 ;;
    esac
    return 1
}

##################
# Error handlers #
##################

handler_EXIT() {
	local exit_code=$?
    [ "$exit_code" -eq 0 ] || echo_error "build have failed"
	exit $exit_code
}

trap handler_EXIT EXIT

#check_warnings:
#    print error message if the compilation had warnings
#argument:
#    $1: log file
check_warnings() {
  #we look for 'warning:' in the compilation log file
  #this is how gcc starts a warning
  #this is not perfect, we may get false positive
  warning_count=`grep "warning:" "$1" | grep -E -v "jobserver unavailable|disabling jobserver mode" | wc -l`
  if [ $warning_count -gt 0 ]; then
    echo_error "WARNING: $warning_count warnings. See $1"
  fi
}

#check_errors:
#    print error message if the compilation had errors
#argument:
#    $1: log file
check_errors() {
  #we look for 'error:' in the compilation log file
  error_count=`grep -c "error:" "$1"`
  if [ $error_count -gt 0 ]; then
    echo_error "ERROR: $error_count error. See $1"
  fi
}

compilations() {
  [[ $# -eq 4 ]] || echo_fatal "compilations <dir> <logfile> <targets> <build-tool-opt>"
  local dir=$1
  local logfile=$2
  local targets=$3
  local build_tool_opt=$4
  local verbose=$([ "$VERBOSE_COMPILE" == "1" ] && echo "-v" || echo "")
  echo cd $OPENAIR_DIR/cmake_targets/$dir/build
  cd $OPENAIR_DIR/cmake_targets/$dir/build
  cmd="$CMAKE --build . ${verbose} --target ${targets} -- ${build_tool_opt}"
  echo_info "Running \"${cmd}\"" $green
  echo "Log file for compilation is being written to: $dlog/$logfile"
  set +e
  {
    eval ${cmd}
    ret=$?
  } > $dlog/$logfile 2>&1
  # Print the errors and warnings for CI purposes
  grep -E -A5 -B5 "warning:|error:| Error " $dlog/$logfile || true
  check_warnings "$dlog/$logfile"
  if [[ $ret -eq 0 ]]; then
     echo_success "$targets compiled"
  else
     check_errors "$dlog/$logfile"
     echo_error "compilation of $targets failed"
     exit 1
  fi
}

############################################
# External packages installers
############################################

check_install_additional_tools (){
  $SUDO $INSTALLER update -y
  local optional_packages=""
  if [[ "$OS_BASEDISTRO" == "debian" ]]; then
    case "$(get_distribution_release)" in
        "ubuntu20.04" | "ubuntu22.04" | "debian11" )
            optional_packages="python3 python3-pip python3-dev python3-scipy python3-matplotlib python3-pyroute2 universal-ctags"
            ;;
    esac
    PACKAGE_LIST="\
        doxygen \
        libgnutls28-dev \
        libpthread-stubs0-dev \
        tshark \
        uml-utilities \
        iperf3 \
        libforms-bin \
        libforms-dev \
        libxml2-dev \
        libxft-dev \
        xmlstarlet"
  elif [[ "$OS_DISTRO" == "rhel" ]] || [[ "$OS_DISTRO" == "centos" ]] || [[ "$OS_DISTRO" == "rocky" ]] ||  [[ "$OS_DISTRO" == "fedora" ]]; then
    PACKAGE_LIST="\
      doxygen \
      ctags \
      iperf3 \
      gnutls-devel \
      libXft-devel \
      xforms \
      xforms-devel \
      xmlstarlet"
  fi
    $SUDO $INSTALLER install -y $PACKAGE_LIST $optional_packages
}

check_install_oai_software() {
    local specific_packages=""
    if ! check_supported_distribution; then
        echo_error "Your distribution $(get_distribution_release) is not supported by ios-mcn !"
        exit 1
    fi
    $SUDO $INSTALLER update -y
  if [[ "$OS_BASEDISTRO" == "debian" ]]; then
    $SUDO apt install -y software-properties-common
    case "$(get_distribution_release)" in
         "debian11")
            specific_packages="libz-dev"
            ;;
    esac
    $SUDO apt-get install -y \
    $specific_packages \
	automake  \
	build-essential \
	$CMAKE \
        ninja-build \
	pkg-config \
	git \
	libblas-dev \
	liblapack-dev \
	liblapacke-dev \
	libreadline-dev \
	libconfig-dev \
	libsctp-dev  \
	libssl-dev  \
	libtool  \
	patch \
	openssl \
	zlib1g-dev \
	xxd \
	libyaml-cpp-dev

  elif [[ "$OS_BASEDISTRO" == "fedora" ]]; then
    if [[ "$OS_DISTRO" == "rhel" ]] || [[ "$OS_DISTRO" == "centos" ]] || [[ "$OS_DISTRO" == "rocky" ]]; then
      if rpm -q epel-release > /dev/null; then
        echo "EPEL repos already present. Good."
      else
        echo "EPEL repos not present. Installing them."
        $SUDO $INSTALLER install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
      fi
    fi

    $SUDO $INSTALLER install -y \
      automake \
      $CMAKE \
      gcc \
      gcc-c++ \
      git \
      pkgconfig \
      libconfig-devel \
      lksctp-tools \
      lksctp-tools-devel \
      libtool \
      ninja-build \
      make \
      openssl-devel \
      patch \
      readline-devel \
      lapack \
      lapack-devel \
      blas \
      blas-devel \
      vim-common \
      zlib-devel \
      yaml-cpp-devel
  fi

    install_asn1c_from_source $1
    install_simde_from_source $1
}

install_asn1c_from_source(){
    mkdir -p log
    asn1_install_log=log/asn1c_install_log.txt
    echo_info "\nInstalling ASN1. The log file for ASN1 installation is here: $asn1_install_log "
    (
    $SUDO $INSTALLER -y install bison flex
    $SUDO rm -rf /tmp/asn1c
    # GIT_SSL_NO_VERIFY=true git clone https://gitlab.eurecom.fr/oai/asn1c.git /tmp/asn1c
    git clone https://github.com/mouse07410/asn1c /tmp/asn1c
    cd /tmp/asn1c
    #git checkout vlm_master
    # hotfix: current vlm_master (5fa129cf3161da9ff2d67341e6277e818c0f5d6a)
    # breaks F1, NG, so use the one before.
    git checkout 940dd5fa9f3917913fd487b13dfddfacd0ded06e
    # Showing which version is used
    git log -n1
    autoreconf -iv
    ./configure --prefix /opt/asn1c/
    make -j`nproc`
    $SUDO make install
    cd -
    $SUDO ldconfig
    if [[ -v CI_ENV ]]; then
        $SUDO rm -rf /tmp/asn1c
    fi
    ) > $asn1_install_log 2>&1
}

install_simde_from_source(){
    echo_info "\nInstalling SIMDE from source without test cases (header files only)"
    cd /tmp
    $SUDO rm -rf /tmp/simde
    git clone https://github.com/simd-everywhere/simde-no-tests.git /tmp/simde
    cd /tmp/simde
    # we can specify a given version of SIMDE (sha-one or tag)
    if [[ -v SIMDE_VERSION ]]; then
      git checkout -f $SIMDE_VERSION
    else
      # At time of writing, last working commit for OAI: 1a09d3bc
      git checkout 1a09d3bc9de47c4d9a5daa23eb753d5322748201
    fi
    # Showing which version is used
    git log -n1
    # brute force copy into /usr/include
    $SUDO \cp -rv ../simde /usr/include
}