uicc0 = {
  imsi = "001010000000007";
  key = "fec86ba6eb707ed08905757b1bb44b8f";
  opc= "c42449363bbad02b66d16bc975d77cc1";
  dnn= "oai";
  nssai_sst=1;
  nssai_sd=0xFFFFFF;
}

rfsimulator: {
  serveraddr = "127.0.0.1";
  serverport = 4043;
  options = ("chanmod");
  modelname = "rfsimu_channel_ue0";
  IQfile = "/tmp/rfsimulator.iqs";
}

channelmod = {
  max_chan = 10;
  modellist = "modellist_rfsimu_1";
  modellist_rfsimu_1 = (
    {
      model_name     = "rfsimu_channel_enB0";
      type           = "AWGN";
      ploss_dB       = 45;
      noise_power_dB = -10;
      forgetfact     = 0;
      offset         = 0;
      ds_tdl         = 0;
    },
    {
      model_name     = "rfsimu_channel_ue0";
      type           = "AWGN";
      ploss_dB       = 45;
      noise_power_dB = -10;
      forgetfact     = 0;
      offset         = 0;
      ds_tdl         = 0;
    }
  );
};
