# /*
# * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# * contributor license agreements.  See the NOTICE file distributed with
# * this work for additional information regarding copyright ownership.
# * The OpenAirInterface Software Alliance licenses this file to You under
# * the OAI Public License, Version 1.1  (the "License"); you may not use this file
# * except in compliance with the License.
# * You may obtain a copy of the License at
# *
# *      http://www.openairinterface.org/?page_id=698
# *
# * Copyright: Fraunhofer Heinrich Hertz Institute
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *-------------------------------------------------------------------------------
# * For more information about the OpenAirInterface (OAI) Software Alliance:
# *      contact@openairinterface.org
# */

FROM ubuntu:22.04 as adapter-dev
LABEL maintainer="adrian.lita@highstreet-technologies.com"

# init ubuntu
RUN apt-get update -y && apt-get upgrade -y

# install tools
RUN DEBIAN_FRONTEND="noninteractive" apt-get install -y \
    # basic tools
    tzdata mc build-essential gdb valgrind git cmake pkg-config doxygen \
    # libyang dependencies
    libpcre2-dev \
    # libssh dependencies
    zlib1g-dev libssl-dev \
    # base dependenceies
    psmisc unzip openssl openssh-client vsftpd openssh-server iproute2 \
    # python things
    python3 python3-six python3-requests python3-pip \
    # libtelnet dependencies
    autoconf libtool

# add netconf user and configure access
RUN \
    adduser --system netconf && \
    echo "netconf:netconf!" | chpasswd

### FTP and SFTP configuration
RUN \
    mkdir /ftp && \
    chown -R netconf /ftp && \
    mkdir /var/run/vsftpd && \
    mkdir /var/run/vsftpd/empty  && \
    mkdir /run/sshd && \
    echo "Match User netconf\n    ChrootDirectory /\n    X11Forwarding no\n    AllowTcpForwarding no\n    ForceCommand internal-sftp -d /ftp" >> /etc/ssh/sshd_config

COPY ./docker/config/vsftpd.conf /etc/vsftpd.conf
COPY ./docker/config/vsftpd.userlist /etc/vsftpd.userlist

RUN \
    mkdir -p /adapter/scripts

# run dependencies install for netconf
COPY ./docker/scripts/netconf_dep_install.sh /adapter/scripts/netconf_dep_install.sh
RUN \
    /adapter/scripts/netconf_dep_install.sh

COPY ./docker/scripts/netconf_dep_install_test.sh /adapter/scripts/netconf_dep_install_test.sh
RUN \
    /adapter/scripts/netconf_dep_install_test.sh

# Initialize netopeer2
RUN \
    /usr/local/share/netopeer2/merge_hostkey.sh && \
    /usr/local/share/netopeer2/merge_config.sh

# get and install required YANG libraries
COPY ./docker/scripts/get-yangs.sh /adapter/scripts/get-yangs.sh
COPY ./docker/scripts/install-yangs.sh /adapter/scripts/install-yangs.sh
RUN \
    cd /adapter/scripts && \
    mkdir yang && \
    ./get-yangs.sh && \
    ./install-yangs.sh

WORKDIR /adapter
CMD ["/bin/sh", "-c", "sleep infinity"]
