services:
    ios-mcn-cucp:
        image: ghcr.io/${REPOSITORY}/ios-mcn-gnb-dis:${VERSION}
        container_name: ios-mcn-cucp
        cap_drop:
            - ALL
        environment:
            USE_ADDITIONAL_OPTIONS: --log_config.global_log_options level,nocolor,time
            ASAN_OPTIONS: detect_leaks=0
        volumes:
            - ../../conf/gnb-cucp.sa.f1-e1.iisc.conf:/opt/oai-gnb/etc/gnb.conf
        network_mode: host
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5

    ios-mcn-cuup:
        image: ghcr.io/${REPOSITORY}/ios-mcn-cuup-dis:${VERSION}  
        container_name: ios-mcn-cuup
        cap_drop:
            - ALL
        environment:
            USE_ADDITIONAL_OPTIONS: --log_config.global_log_options level,nocolor,time
            ASAN_OPTIONS: detect_leaks=0
        depends_on:
            - ios-mcn-cucp
        network_mode: host
        volumes:
            - ../../conf/gnb-cuup.sa.f1-e1.iisc.conf:/opt/oai-gnb/etc/gnb.conf
        healthcheck:
            test: /bin/bash -c "pgrep nr-cuup"
            interval: 10s
            timeout: 5s
            retries: 5

    ios-mcn-du:
        image: ghcr.io/${REPOSITORY}/ios-mcn-gnb-dis:${VERSION}
        container_name: ios-mcn-du
        privileged: true
        cap_drop:
            - ALL
        ulimits:
          core: -1 # for core dumps
        environment:
            USE_B2XX: 'yes'
            USE_ADDITIONAL_OPTIONS: --RUs.[0].sdr_addrs serial=31D4A34
                                    --continuous-tx -E
                                    --gNBs.[0].min_rxtxtime 6 --gNBs.[0].do_CSIRS 1 --gNBs.[0].do_SRS 1
                                    --RUs.[0].att_rx 14 --RUs.[0].att_tx 14
                                    --log_config.global_log_options level,nocolor,time,line_num,function
        depends_on:
            - ios-mcn-cucp
            - ios-mcn-cuup
        network_mode: host
        devices:
            - /dev/bus/usb/:/dev/bus/usb/
        volumes:
            - ../../conf/gnb-du.sa.band78.106PRB.1x1-f1-e1-usrpb210.conf:/opt/oai-gnb/etc/gnb.conf
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5
