services:
  adapter-gnb-du:
    image: ghcr.io/${REPOSITORY}/adapter-gnb:${VERSION}
    container_name: adapter-gnb-du
    command: ["--du", "-c", "/docker/config/du_config.json"]
    volumes:
      - ../../conf/o1-config/config:/docker/config
    ports:
      - "830:830"
      - "2222:22"   # changed host SSH port from 24 to 2222 (optional)
    restart: unless-stopped
