name: Run Test Cases

on:
  push:
    tags:
      - 'v*'  # Triggers only on tags starting with 'v' like v1.0, v2.1.3 etc.

jobs:
  authcheck:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      DOCKER_REGISTRY: ghcr.io/
      DOCKER_REPOSITORY: ${{ github.repository_owner }}/
    steps:
      - uses: actions/checkout@v3

      - name: Login to ghcr Hub
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GHCRUSER }}
          password: ${{ secrets.GHCRPASS }}
  run-tests:
    runs-on: ubuntu-latest
    needs: authcheck
    env:
        REGISTRY: ghcr.io
        DOCKER_REGISTRY: ghcr.io/
        DOCKER_REPOSITORY: ${{ github.repository_owner }}/
    steps:
      - name: Login to ghcr Hub
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GHCRUSER }}
          password: ${{ secrets.GHCRPASS }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" \
            -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Set up Docker (optional)
        run: |
          sudo systemctl start docker
          docker info

      - name: List XML files
        run: |
          ls -l cicd/xml_files || echo "No xml_files directory found"

      - name: Run Test Execution Script
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}/
          IMAGE_VERSION: ${{ github.ref_name }}
        run: |
          python3 cicd/scripts/5g_rfsim_docker.py
